name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Initialize pgrx
        run: cargo pgrx init

      - name: Run tests
        run: cargo pgrx test --verbose

      - name: Package
        run: cargo pgrx package
